### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by IogaMaster** [hyprwm/hypridle#1]
![image](https://github.com/hyprwm/hypridle/assets/67164465/f7df7fe0-6270-4d36-a118-5a024e55cffb)

``` ./result/bin/hypridle
terminate called after throwing an instance of 'char const*'
Aborted: oops, process './result/bin/hypridle' core dumped
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #17:1:1]
 1 │ ./result/bin/hypridle
   · ──────────┬──────────
   ·           ╰── core dumped
   ╰────
  help: Aborted: child process './result/bin/hypridle' core dumped
```

**Comment by IogaMaster** [comment]
built with `nix build github:hyprwm/hypridle`

**Comment by wiillou** [comment]
built with `nix build github:hyprwm/hypridle` as well and i got the same error on my machine

**Comment by fufexan** [comment]
Fixed in https://github.com/hyprwm/hypridle/commit/c8e0016fa562996aef7e7fcea9b7ebc3cf6a7e90
