### ISSUE TITLE
hypridle: error while loading shared libraries: libsdbus-c++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/hypridle#101]
when i run "hypridle"

i get error "hypridle: error while loading shared libraries: libsdbus-c++.so.1: cannot open shared object file: No such file or directory"

**Comment by vaxerski** [comment]
recompile

**Comment by mooncoffee1** [comment]
i use it on arch linux, its the prebuild package, u mean to reinstall the hypridle package?

**Comment by vaxerski** [comment]
if you are not using the aur then either you did a partial rebuild, your mirrors are broken, or the arch packagers fucked up.

**Comment by mooncoffee1** [comment]
> if you are not using the aur then either you did a partial rebuild, your mirrors are broken, or the arch packagers fucked up.

i think its the last option, the hypridle nor the hypridle-git version works, for non git version it runs but no idle, and the -git version, just doesnt even wanna run, and gives the error from the title of this issue
