### ISSUE TITLE
Never receiving ScreenSaver inhibit: false dbus message from Firefox for video-playing

### ISSUE THREAD

**Issue by polaris64** [hyprwm/hypridle#103]
I'm not sure if this is a Hypridle problem or a Firefox problem, so apologies in advance if it's the latter.

I've been using Hypridle for a few months now and it has been working perfectly, however after a recent update I've noticed that it no longer works properly, specifically after I've watched a video in Firefox.

Checking the Hypridle logs I see lots of message like: -

```
[...]
[LOG] ScreenSaver inhibit: true dbus message from  (owner: :1.19) with content video-playing
[LOG] Inhibit locks: 152
[LOG] Cookie 1491 sent
[LOG] ScreenSaver inhibit: true dbus message from  (owner: :1.19) with content video-playing
[LOG] Inhibit locks: 153
[LOG] Cookie 1492 sent
[...]
```

These are triggered when I start a video (YouTube) playing in Firefox. The number of inhibit locks just increases as it looks like the matching `false` message (when the video is stopped) is never received. This has the effect of inhibiting my usual screen locking and DPMS off actions.

As I mentioned, this happened after a recent update, however I'm not sure if it was a Hypridle or Firefox update which changed things as I only noticed it a few days later.

For reference I'm using: -

Arch Linux: `Linux tikal 6.11.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000 x86_64 GNU/Linux`
`hypridle 0.1.4-1` (from the Arch package repositories)
```
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3
```

**Comment by vaxerski** [comment]
tried hypridle-git?

**Comment by polaris64** [comment]
> tried hypridle-git?

Hi @vaxerski, thanks for the suggestion. I've just tried and yes it appears to work now: -

```
[LOG] ScreenSaver inhibit: true dbus message from firefox (owner: :1.64) with content video-playing
[LOG] Inhibit locks: 1
[LOG] Cookie 1337 sent
[LOG] ScreenSaver inhibit: true dbus message from  (owner: :1.19) with content video-playing
[LOG] Inhibit locks: 2
[LOG] Cookie 1338 sent
[LOG] ScreenSaver inhibit: false dbus message from firefox (owner: :1.64) with content video-playing
[LOG] Inhibit locks: 1
[LOG] ScreenSaver inhibit: true dbus message from firefox (owner: :1.64) with content video-playing
[LOG] Inhibit locks: 2
[LOG] Cookie 1339 sent
[LOG] ScreenSaver inhibit: false dbus message from firefox (owner: :1.64) with content video-playing
[LOG] Inhibit locks: 1
[LOG] ScreenSaver inhibit: false dbus message from  (owner: :1.19) with content video-playing
[LOG] Inhibit locks: 0
```

Thanks for your work on all the Hypr applications!

**Comment by vaxerski** [comment]
closing then
