### ISSUE TITLE
ext-idle-notify-v1 does not always seem to work

### ISSUE THREAD

**Issue by botn365** [hyprwm/hypridle#107]
OS: Linux 6.11.5-arch1-1
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
hypridle 0.1.4-1

My understanding of how hypridle works
Is by using [ext_idle_notifier_v1](https://wayland.app/protocols/ext-idle-notify-v1#ext_idle_notifier_v1) to listen for idle
And separately is pulling for inhibitors increasing or decreasing m_iInhibitLocks if their is a new lock or geting removed
```cpp
void CHypridle::onInhibit(bool lock) {
    m_iInhibitLocks += lock ? 1 : -1;
```
Then when `idled` or `removed` gets called it checks  if their are any inhabitor locks
```cpp
if (g_pHypridle->m_iInhibitLocks > 0) {
```
When trying to implement #39 it seems like only steam was getting loged
[log.txt](https://github.com/user-attachments/files/17615087/log.txt)
But when watching a youtube video or starting factorio they send nothing in the logs
But `idled` would completely be stopped being called even when putting a break point in `onIdled`
Even setting ignore_dbus_inhibit and ignore_systemd_inhibit to true does not stop firefox/youtube or factorio from inhabiting idle

**Comment by vaxerski** [comment]
what?

**Comment by botn365** [comment]
okay im just stupid i should have looked around more to find [zwp_idle_inhibit_manager_v1](https://wayland.app/protocols/idle-inhibit-unstable-v1#zwp_idle_inhibit_manager_v1)
