### ISSUE TITLE
Monitor doesn't go to sleep while system in suspend mode

### ISSUE THREAD

**Issue by herzoid** [hyprwm/hypridle#110]
After recent system updates, the monitor does not go to sleep when the system is suspended. It should be noted that monitor goes to sleep flawlessly during system idle. In my config file, hypridle.conf, there is a line "after_sleep_cmd = hyprctl dispatch dpms on". Its taken from hyprwiki. If I manually suspend the system by command "systemctl suspend", the monitor goes to sleep. However, if the system goes to sleep according to the hypridle configuration, the monitor doesn't enter sleep mode. I discovered that if this line is commented out, the monitor successfully enters sleep mode when the system suspends. This issue may be related to NVIDIA drivers, as it occurred after a recent system update. If it is important to note: the NVIDIA RTX 3060 card and HP 24" monitor are connected via a DisplayPort cable.

config file content after editing (monitor goes to sleep with this config) - the fourth line was commented out.

```conf
general {
   # lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
   # before_sleep_cmd = loginctl lock-session    # lock before suspend.
   # after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 600                                 # 10min
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
```

**Comment by sofijacom** [comment]
I'll tell you guys, everything worked fine until everyone here started building their own modes for their own computer, as a result, now none of my computers work.
