### ISSUE TITLE
Screen Locks while gaming on lutris with a controller

### ISSUE THREAD

**Issue by anmolsekhon590** [hyprwm/hypridle#114]
So I'm playing Rocket League with a controller and the screen keeps locking. I believe hypridle doesn't register controller inputs before locking the screen.

Game: Rocket League
Distro: Arch linux
Kernel: mainline 6.12.1 kernel 
WM: Hyprland
Controller: PS5 Dual Sense
wine version: 9.22 (wine-staging) package via pacman
Locking utility: Hyprlock

**Comment by vaxerski** [comment]
that's not up to hypridle. Hypridle doesn't see your apps. It's likely that the game itself isn't registering an idle inhibitor. Add a windowrule for it.

**Comment by anmolsekhon590** [comment]
@vaxerski could you please explain what sort of window rule do I need to prevent it?

**Comment by vaxerski** [comment]
idleinhibit. check the wiki.
