### ISSUE TITLE
Please Fix the 'Doesn't work till locked once manually'

### ISSUE THREAD

**Issue by JulesDmn** [hyprwm/hypridle#21]
diff --git a/src/core/Hypridle.cpp b/src/core/Hypridle.cpp
index af317e8..9469ce0 100644
--- a/src/core/Hypridle.cpp
+++ b/src/core/Hypridle.cpp
@@ -69,6 +69,8 @@ void CHypridle::run() {
         ext_idle_notification_v1_add_listener(l.notification, &idleListener, &l);
     }
 
+    wl_display_roundtrip(m_sWaylandState.display);
+
     Debug::log(LOG, "wayland done, registering dbus");
 
     try {

**Comment by vaxerski** [comment]
?

if you believe that will fix it I welcome you to make a mr
