### ISSUE TITLE
Best practice configuration for suspend on laptop and desktop pc

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/hypridle#28]
Thanks for your great work on hypridle.

Can you share a best practice setup for starting hyprlock and suspend mode for desktops and laptops on Arch?

Would be super helpful for many users.

**Comment by vaxerski** [comment]
I don't think there exists a best practice?

dpms off for a screensaver, systemctl suspend for a suspend, I guess?

I don't use suspend, my laptop automatically does it when lid is closed.

**Comment by mylinuxforwork** [comment]
I think a working example configuration covering hyprlock and suspend with a proposal from your side would be super helpful for many users. This is currently the most used use case I would guess.

**Comment by vaxerski** [comment]
that's already there:

https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/#listeners

**Comment by mylinuxforwork** [comment]
Awesome. Thank you.

**Comment by znd4** [comment]
> that's already there:
> https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/#listeners

It could be worth linking to this from the README (for dummies like me, who didn't understand that you need to define a listener for this to do anything)
