### ISSUE TITLE
[REQ] Put this on the AUR

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hypridle#3]
Just a reminder, I guess it would make sense to put this here

I could do it myself, if you'd like that, but I assume you'd prefer to keep it with the other ones

**Comment by vaxerski** [comment]
I dont maintain aur stuff and it's up to ya (the community) to do it

**Comment by alba4k** [comment]
Oh, sorry, I saw this https://github.com/hyprwm/aur and assumed this stuff was being managed by you

Brb then, gotta publish something really fast ;)

**Comment by alba4k** [comment]
@vaxerski what should the version be?

**Comment by vaxerski** [comment]
> Oh, sorry, I saw this https://github.com/hyprwm/aur and assumed this stuff was being managed by you

Old repo made back when kainoa was managing da aur.

> @vaxerski what should the version be? I was thinking maybe 0.0.1.r13.5541017-1?

cmake ver is 0.1.0. I'll make a release soon too with that.

**Comment by alba4k** [comment]
Ok fixed, it is now `0.1.0.r0.gcd592840-1`

I will close this unless you have anything else to add

**Comment by vaxerski** [comment]
nope can be closed, thanks!
