### ISSUE TITLE
Hypridle ignores dbus inhibits and systemd-inhibits

### ISSUE THREAD

**Issue by Xenfo** [hyprwm/hypridle#32]
When Firefox plays media, Hypridle doesn't listen to the dbus events to prevent idle. I solved this using https://github.com/loops/idlehack on Swayidle but it seems that Hypridle ignores systemd-inhibits too so it doesn't work anymore.

**Comment by Cody-W-Tucker** [comment]
Do you get any errors when you run `xdg-open https://example.com`?

Hypridle uses org.freedesktop.ScreenSaver to check for systemd-inhibits. If your desktop environment doesn't provide the ScreenSaver service, it can't inhibit idle.

**Comment by Xenfo** [comment]
I don't get any errors running `xdg-open` but I do get this when running `hypridle`. I haven't noticed it since I run it at startup.

```
[LOG] wayland done, registering dbus
[LOG] Using dbus path /org/freedesktop/login1/session/_313
[ERR] Failed registering for /org/freedesktop/ScreenSaver, perhaps taken?
err: [org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists)
```

**Comment by fufexan** [comment]
@Xenfo you can check which program took that name with `busctl --user status org.freedesktop.ScreenSaver`.

**Comment by Xenfo** [comment]
So it was taken by `idlehack` which I've now uninstalled. Thank you!
