### ISSUE TITLE
Unable to enter password when resuming from standby mode

### ISSUE THREAD

**Issue by sofijacom** [hyprwm/hypridle#36]
After exiting the standby mode, the password is entered incorrectly because when I try to enter the password, instead of one pressed symbol, three are entered at once. It’s as if I pressed it three times.

**Comment by vaxerski** [comment]
that has been fixed an eternity ago

**Comment by sofijacom** [comment]
This behavior is on Void-linux version hyprland-0.36.0_1

**Comment by sofijacom** [comment]
> это было исправлено вечность назад

This behavior is on Void-linux version hyprland-0.36.0_1
