### ISSUE TITLE
[Bug] error while loading shared libraries: libhyprlang.so.1

### ISSUE THREAD

**Issue by NextStep-IM** [hyprwm/hypridle#40]
**Distro:** Arco Linux

**Bug Description:**
hypridle hasn't been working for a while now. Running it from terminal gives this error: `hypridle: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory`

I am using `hypridle-git` from AUR. The one in the `extra` repo runs but does not trigger `hyprlock`. Terminal output: 
```plain
[LOG] found 3 rules
[LOG] wayland done, registering dbus
[LOG] Using dbus path /org/freedesktop/login1/session/_35
[LOG] Idled: rule 5769e45bdb60
[LOG] Running pidof hyprlock || hyprlock
[LOG] Executing pidof hyprlock || hyprlock
[LOG] Process Created with pid 522685
278885 272338
```

**Comment by vaxerski** [comment]
this is an error on your side, you have broken packages. Update hyprlang and recompile hypridle...
