### ISSUE TITLE
Run a command elevated (sudo) ?

### ISSUE THREAD

**Issue by dimitrisfasoulas** [hyprwm/hypridle#42]
Is it possible to invoke a script with sudo ?

I have a script that restarts a service. The script is added in sudoers:
`myusername ALL=(ALL) NOPASSWD: /home/myusername/script.sh` 
and I'm able to invoke it with sudo without requiring password. But if I added to the listener like so: 

```
# Screenlock
listener {
    # HYPRLOCK TIMEOUT
    timeout = 600
    # HYPRLOCK ONTIMEOUT
    on-timeout = hyprlock
    on-resume = sudo -u myusername /home/myusername/script.sh ; 
}
```

I get a prompt to provide sudo password.

**Comment by vaxerski** [comment]
`echo [PASSWORD] | sudo -S <cmd>`?

**Comment by fjueic** [comment]
> aaah ... that might work, but I think I prefer typing the password each time than hardcoding it to a script :)

`pkexec <cmd>`

**Comment by simonm** [comment]
Add the script or service to `/etc/sudoers` using ``visudo`. Or add a config file to /etc/sudoers.d

Format like this:

``
`yourusername ALL=(ALL) NOPASSWD: /home/yourusername/script.sh
```

**Comment by dimitrisfasoulas** [comment]
Thnx simonm but if you look at my original post I've already added the script to sudoers:

> I have a script that restarts a service. The script is added in sudoers:
myusername ALL=(ALL) NOPASSWD: /home/myusername/script.sh

**Comment by simonm** [comment]
Yes. My bad. Sorry about that
