### ISSUE TITLE
hypridle doesn't respect systemd-inhibit inhibitors

### ISSUE THREAD

**Issue by kelvie** [hyprwm/hypridle#43]
I think you have to implement something like this for swayidle: https://github.com/swaywm/swayidle/pull/48

To reproduce:

```
systemd-inhibit --what=idle --who=me --why="testing reasons" sleep infinity
```

And watch hypridle still lock (it's easy to test with this conf file:

```
listener {
    timeout = 2
    on-timeout = notify-send "idle"
    on-resume = notify-send "resumed"
}
```

**Comment by yawor** [comment]
#57 has been merged. This issue can be closed now.
