### ISSUE TITLE
[NixOS] Vivaldi Doesn't load correctly

### ISSUE THREAD

**Issue by Aman9das** [hyprwm/hypridle#52]
```
Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.UnknownMethod: Unknown method GetActive or interface org.freedesktop.ScreenSaver.
```

With the latest nixpkgs update vivaldi errors out this.

**Comment by fufexan** [comment]
Are you sure hypridle is running? I can check `d-spy` and the method is there and works fine.

**Comment by Aman9das** [comment]
Rebasing back to prior release fixes it, or using Cinnamon fixes it. I'll try swaylock and tell results

**Comment by Aman9das** [comment]
false report. freedesktop error shouldn't cause problems previous version doesn't break even with this error.
