### ISSUE TITLE
Configuration option to do nothing when a fullscreen app is present?

### ISSUE THREAD

**Issue by krims0n32** [hyprwm/hypridle#53]
When playing a game through wine (xwayland, outside of Steam), hypridle still does its thing locking my screen and suspending my system.

I can probably hack a workaround into hypridle.conf by checking `hyprctl clients` output for `fullscreen: 1` in the `on-timeout` section but perhaps a configuration option for this would be a nicer solution?

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/hypridle/assets/43317083/f3c8f95d-082f-4326-93c7-e89c6efa6a50)
rtfm https://wiki.hyprland.org/Configuring/Window-Rules/
