### ISSUE TITLE
[Feature] Listen to key bind

### ISSUE THREAD

**Issue by Aqa-Ib** [hyprwm/hypridle#54]
A listener to a key bind would allow us to power off our screens using a key bind, and power them on again with a key press.

**Comment by fufexan** [comment]
Can already be done from Hyprland.

**Comment by Aqa-Ib** [comment]
How ?

**Comment by fufexan** [comment]
`bind = $mod, D, dpms, toggle`. https://wiki.hyprland.org/Configuring/Dispatchers

**Comment by Aqa-Ib** [comment]
Thanks for your reply. Although, `dpms toggle` seems broken on hyprland-git and v.0.39.1. Does it work for you?

**Comment by fufexan** [comment]
Right. It seems to turn off the displays but not turn them back on.

**Comment by Aqa-Ib** [comment]
I managed to make it work with two bindings: one for `dpms off` and another for `dpms on`. I will fill a bug on Hyprland about `dpms toggle` though. Thank you for the hint, have a nice one !
