### ISSUE TITLE
Idle inhibit event for a program that doesn't do them

### ISSUE THREAD

**Issue by dxwil** [hyprwm/hypridle#55]
I have an ereader program, and I would like it so when that program is on screen, hypridle wouldn't sleep. Same way when watching youtube videos, but firefox sends idle inhibit events, but my ereader program doesn't. How could I achieve this?

**Comment by vaxerski** [comment]
rtfm plague #53

**Comment by dxwil** [comment]
Added the following line to my hyprland config and all works now, thanks

`windowrulev2 = idleinhibit focus, class: (com.github.johnfactotum.Foliate)`
