### ISSUE TITLE
not getting inhibited by waybar idle inhibitor

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/hypridle#61]
Even waybar idle inhibitor is enabled, hypridle triggers lock screen and system suspend

**Comment by vaxerski** [comment]
wasnt that a bug in hyprland 0.40 and fixed in git?

**Comment by niksingh710** [comment]
Uhh .... Yeah ur right .... 
I forgot that I switched to stable version as u r working on xwayland/clipboard MR
