### ISSUE TITLE
on-timeout runs over and over again

### ISSUE THREAD

**Issue by se7en-x230** [hyprwm/hypridle#65]
listener {
    timeout = 5                                                        # in seconds
    on-timeout = hyprlock.sh                               # command to run when timeout has passed

I see that the script runs ever 5 second and not only once. What am I doing wrong?

**Comment by fufexan** [comment]
That's how it's supposed to work, if you are idle (no mouse movement/keys pressed/videos playing).

**Comment by se7en-x230** [comment]
okey I thought the command runs once ...
Why would it run over and over again?

**Comment by fufexan** [comment]
It is expected that once you're idle for 5 seconds, it will run. If you're not idle but it still runs, that's an issue.

**Comment by se7en-x230** [comment]
must be my script 

I replaced it with 
`now="$(date +"%T")"
echo "Current time : $now" >> $HOME/log`

and that executes only once.

**Comment by vaxerski** [comment]
it should run once and never again until you are back from idle and idle again for 5 seconds iirc, but it would suggest a hyprland bug rather than hypridle if thats not the case
