### ISSUE TITLE
[Question] Can i somehow setup hypridle to suspend on battery, but not on charge?

### ISSUE THREAD

**Issue by KomaDi** [hyprwm/hypridle#66]
I have a laptop and want to have suspend only on battery. Is it even possible?

**Comment by fufexan** [comment]
Run a script that checks whether you're on battery, and only suspends if that's the case.

**Comment by KomaDi** [comment]
> Run a script that checks whether you're on battery, and only suspends if that's the case.

How do i create that script? I'm newbie in linux and actually don't know how to manage sh scripts.

**Comment by KomaDi** [comment]
Okay, i made a sh file but i don't know how to activate this for hypridle

`ac_adapter="$(cat /sys/class/power_supply/ACAD/online)"

if [[ ac_adapter -eq 0 ]];

then

notify-send -u low "Amogus"

fi`
P.S. notify-send is just for test
