### ISSUE TITLE
[BUG] Resume from hibernation does not reset timers

### ISSUE THREAD

**Issue by marvinjuette** [hyprwm/hypridle#69]
Hej,

I started using hypridle to put my system to hibernate after a certain amount of time (e.g. 20 minutes). But when I put my system into hibernation state manually and turn it on and resume later on (the time limit needs to be exceeded), hypridle seems to recognize that the timer for hibernation is overdue and immediately puts my system back into hibernation. After a second boot/resume, the system stays awake because the hypridle action is not triggered again.

Since I commented out the config for hibernation, the issue was resolved.

The behavior I expected would be, that (all) timers of hypridle would be reset, after a boot/resume from a hibernated state.

**Comment by vaxerski** [comment]
this is an issue with your compositor, presumably hyprland?
