### ISSUE TITLE
automatic reload

### ISSUE THREAD

**Issue by Atemu** [hyprwm/hypridle#70]
Currently, in order for a change in the hypridle config to apply, one must kill the daemon and re-run it.

It'd be great if hypridle would automatically reload the config when it changes; just like Hyprland.

**Comment by vaxerski** [comment]
no point, restarting it is trivial

**Comment by Atemu** [comment]
Not quite, one must resort to hacks like `nohup` which is annoying to deal with as it litters every directory with `.nohup` files unless you do the `nohup ... > /dev/null` dance.

Or is there some other method I'm missing?

**Comment by vaxerski** [comment]
`killall hypridle && hypridle&disown`

**Comment by Atemu** [comment]
That's a good bit better.

Though I'd still like auto reload for the convenience alone.

**Comment by vaxerski** [comment]
write a script to get the last modified date every second and execute above if it changes?

**Comment by Atemu** [comment]
Sure you could do that but at that point you might aswell use a service manager...

**Comment by vaxerski** [comment]
you know that's precisely how it works in hyprland though? xD

**Comment by Atemu** [comment]
Sorry, I'm not following; how what works in Hyprland?

**Comment by vaxerski** [comment]
auto-reload. It `stat`s the files every second and reloads if modified date changed

**Comment by Atemu** [comment]
Ah, yes of course that's how it'd have to work. Though in this case, it'd be integrated into the daemon itself and merely "reloads" rather than tearing everything down and bringing it up again. In the case of Hyprland, tearing it down is simply not possible without user interruption, so that's the only solution while here we can simply restart the daemon without any loss to the user.
